export const globalError = {
  ADD_AD_FAILED: 'La finalisation de l\'ajout de votre bénéficiaire n\'a pas abouti, veuillez réessayer ultérieurement.',
  CANCEL_ADD_AD_FAILED: 'L\'annulation de l\'ajout de votre bénéficiaire n\'a pas abouti, veuillez réessayer ultérieurement.',
  CANCEL_DELETE_AD_FAILED: 'L\'annulation de la suppression de votre bénéficiaire n\'a pas abouti, veuillez réessayer ultérieurement.',
  CANCEL_PROJET_FAILED: 'Une erreur est survenue lors du refus du projet, veuillez réessayer ultérieurement.',
  CAN_ADD_AD_FAILED: 'L\'ajout de l\'ayant droit du salarié n\'est pas possible, veuillez réessayer ultérieurement.',
  CHANGE_FISCALITE_FAILED: 'La mise à jour de votre fiscalité Madelin n\'a pas abouti, veuillez réessayer ultérieurement.',
  CONNEXION_FAILED: 'La connexion n\'a pas abouti, veuillez réessayer ultérieurement.',
  DELETE_AD_FAILED: 'La radiation de votre bénéficiaire n\'a pas pu être prise en compte, veuillez réessayer ultérieurement.',
  DOWNLOAD_DOC_FAILED: 'Le service de téléchargement des documents est indisponible pour le moment, veuillez réessayer ultérieurement.',
  ENTREPRISE_CREATE_PARCOURS_PREVOYANCE: 'La création de la signature électronique n\'a pas abouti, veuillez réessayer ultérieurement.',
  ENTREPRISE_GET_PARCOURS_PREVOYANCE: 'La récupération de la signature électronique n\'a pas abouti, veuillez réessayer ultérieurement.',
  ENTREPRISE_SALARIE_ADD_FAILED: 'Le service d\'affiliation est momentanément indisponible , veuillez réessayer ultérieurement.',
  ENTREPRISE_SALARIE_AD_ADD_FAILED: 'L\'ajout de l\'ayant droit du salarié n\'a pas abouti, veuillez réessayer ultérieurement.',
  SALARIE_AD_ADD_FAILED: 'L\'ajout de l\'ayant droit n\'a pas abouti, veuillez réessayer ultérieurement.',
  ENTREPRISE_SALARIE_DELETE_FAILED: 'La suppression d\'un salarié n\'a pas abouti, veuillez réessayer ultérieurement.',
  ENTREPRISE_SALARIE_GET_FAILED: 'Le chargement des données d\'un salarié n\'a pas abouti, veuillez réessayer ultérieurement.',
  GEDAMA_CONVERSION_PDF_FAILED: 'Le service de conversion des documents en PDF est momentanément indisponible, veuillez réessayer ultérieurement.',
  GET_AD_FAILED: 'L\'affichage de vos bénéficiaires n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_AFFILIATION_EN_ATTENTE_FAILED: 'Le service d\'affiliation est momentanément indisponible , veuillez réessayer ultérieurement.',
  GET_AFFILIATION_EN_COURS_FAILED: 'Le service d\'affiliation est momentanément indisponible , veuillez réessayer ultérieurement.',
  GET_AFFILIATION_JUSTIFICATIFS_FAILED: 'Le chargement des justificatifs n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_AFFILIATION_SALARIE_FAILED: 'Le chargement des informations liées à l\'affiliation salarié n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_ALL_CAISSES_FAILED: 'Le chargement des paramètres n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_ALL_CENTRES_FAILED: 'Le chargement des paramètres n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_ALL_CIVILITES_FAILED: 'Le chargement des civilités, n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_ALL_COLLEGES_CLEVA_FAILED: 'Le chargement des paramètres n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_ALL_COLLEGES_FAILED: 'Le chargement des collèges, n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_ALL_ETATS_AFFILIES_CLEVA_FAILED: 'Le chargement des salariés n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_ALL_GENRES_FAILED: 'Le chargement des paramètres n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_ALL_GRAND_REGIMES_FAILED: 'Le chargement des paramètres n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_ALL_RISQUES_FAILED: 'Le chargement des paramètres n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_ALL_SITUATIONS_FAMILIALES_FAILED: 'Le chargement des paramètres n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_APPORTEURS_FAILED: 'Le chargement de apporteurs, n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_ARRAY_ASSURE: 'Nous ne sommes pas en mesure d\'afficher votre tableau de garanties, veuillez réessayer ultérieurement.',
  GET_COMPTE_BANCAIRE_FAILED: 'Le chargement des informations du compte bancaire n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_CONTRAT_FAILED: 'Le service de restitution de vos contrats est momentanément indisponible, veuillez réessayer ultérieurement.',
  GET_COORDONNEES_BANCAIRE_FROM_CLEVA_FAILED: 'Le chargement des coordonnées bancaire à partir de Cleva, n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_CP_VILLE_FAILED: 'Le chargement des paramètres n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_DOCUMENTS_CONTRACTUELS_FAILED: 'Le chargement des documents contractuels, n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_DOCUMENTS_FAILED: 'Le chargement des documents n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_DOCUMENTS_TYPES_AFFILIATION_FAILED: 'Le chargement des documents n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_DOCUMENT_BY_CATEGORIES_FAILED: 'Le chargement des documents n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_ENTREPRISES_CLEVA_FROM_TNS_FAILED: 'Le chargement des entreprises n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_FAQS_BY_PROFIL_CODE_FAILED: 'Le chargement de la FAQ n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_FAQS_BY_PROFIL_FAILED: 'Le chargement de la FAQ n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_FAQ_GROUPES_FAILED: 'Le chargement de la FAQ n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_FAQ_OBJETS_FAILED: 'Le chargement de la FAQ n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_FIRST_ACTIF_CONTRAT_SANTE_NUMBER_FAILED: 'Le service de restitution de vos contrats est momentanément indisponible, veuillez réessayer ultérieurement.',
  GET_FORMALITES_MEDICALES_FAILED: 'Le chargement de formalités médicales, n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_FORMULES_AFFILIE_FAILED: 'Le chargement des contrats n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_FORMULES_FAILED: 'Le chargement des contrats n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_INFO_ENTRE_FAILED: 'Le service de restitution des données de votre entreprise est momentanément indisponible, veuillez réessayer ultérieurement.',
  GET_INFO_PERSO_FAILED: 'Le service de restitution de vos données personnelles est momentanément indisponible, veuillez réessayer ultérieurement.',
  GET_INVOICE_FAILED: 'Le service de restitution de vos cotisations est momentanément indisponible, veuillez réessayer ultérieurement.',
  GET_LIENS_UTILES_BY_ENTITE_FAILED: 'Le chargement des liens utiles, n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_PARAMETRAGE_ENTITE_FAILED: 'Le chargement des paramètres n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_PARAMETRAGE_SELFCARE_FAILED: 'Le chargement des paramètres n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_PRELEVEMENTS_COTISATION_FUTURS: 'Le chargement des informations du prélévement n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_PROJET_FAILED: 'Nous ne sommes pas en mesure d\'afficher le détail de votre projet, veuillez réessayer ultérieurement.',
  GET_PROJET_PDF_BY_ID_FAILED: 'Le chargement du document n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_STRUCTURES_COTISATION_FAILED: 'Le chargement des taux de cotisation n\'a pas abouti, veuillez réessayer ultérieurement.',
  GET_TELE_TRANS_FAILED: 'La restitution de l\'indicateur de télétransmission n\'a pas abouti, veuillez réessayer ultérieurement.',
  HAS_MANDAT_COMPTE_BANCAIRE_FAILED: 'Le chargement des paramètres n\'a pas abouti, veuillez réessayer ultérieurement.',
  NOTIFICATION_FAILED: 'Le service de notifications est indisponible pour le moment, veuillez réessayer ultérieurement.',
  NOT_FOUND: 'Le service est momentanément indisponible, veuillez réessayer ultérieurement.',
  SEARCH_AD_FAILED: 'La recherche de votre bénéficiaire n\'a pas abouti, veuillez réessayer ultérieurement.',
  SEARCH_IS_DUPLICATED_SALARIE_FAILED: 'La recherche d\'un salarié en doublon a échoué, veuillez réessayer ultérieurement.',
  SEND_FAQ_DYNAMIQUE_FAILED: 'Une erreur est survenue lors de l\'envoi de votre demande, veuillez réessayer ultérieurement.',
  SEND_MAIL_FAILED: `L'envoi du mail a échoué.`,
  SEND_MAIL_RELANCE_EMAIL_NOT_FOUND: 'E-mail non renseigné pour:',
  SEND_MAIL_RELANCE_FAILED: 'Le service d\'envoi d\'e-mails est momentanément indisponible, veuillez réessayer ultérieurement.',
  SIGNATURE_FAILED: 'Le service de signature électronique est momentanément indisponible, veuillez réessayer ultérieurement.',
  TECHNICAL_ERROR: 'Le service est momentanément indisponible, veuillez réessayer ultérieurement.',
  UPDATE_ADDRESS_FAILED: 'La mise à jour de votre adresse n\'a pas abouti, veuillez réessayer ultérieurement.',
  UPDATE_AD_FAILED: 'La modification de votre bénéficiaire n\'a pas abouti, veuillez réessayer ultérieurement.',
  UPDATE_DATE_DERNIERE_VISITE_PAGE_MES_DOCUMENTS_FAILED: 'La mise à jour de la date de la dernière visite, n\'a pas abouti, veuillez réessayer ultérieurement.',
  UPDATE_IBAN_FAILED: 'La mise à jour de vos coordonnées bancaires n\'a pas abouti, veuillez réessayer ultérieurement.',
  UPDATE_INFO_ENTR_FAILED: 'La mise à jour des données de votre entreprise n\'a pas abouti, veuillez réessayer ultérieurement.',
  UPDATE_INFO_PERSO_FAILED: 'La mise à jour de vos données personnelles n\'a pas abouti, veuillez réessayer ultérieurement.',
  UPDATE_PAYMENT_METHODE_FAILED: 'La mise à jour de vos options de paiement n\'a pas abouti, veuillez réessayer ultérieurement.',
  UPDATE_REGIM_OBLIG_FAILED: 'La mise à jour de votre organisme de rattachement n\'a pas abouti, veuillez réessayer ultérieurement.',
  UPDATE_TELE_TRANS_FAILED: 'La mise à jour de votre indicateur de télétransmission n\'a pas abouti, veuillez réessayer ultérieurement.',
  UPLOAD_DOC_FAILED: 'Le service de chargement des pièces justificatives est indisponible pour le moment, veuillez réessayer ultérieurement.',
  VALIDATION_AFFILIATION_SANTE_FAILED: 'La validation de l\'affiliation de votre salarié a échoué, veuillez réessayer ultérieurement.',
  VERIFY_DOUBLON_AFFILIATION_AD_FAILED: 'L\'affiliation du bénéficiaire n\'a pas abouti, veuillez réessayer ultérieurement.'
};
